//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _50_Ders_MVC_Projesi.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int MUSTERIID { get; set; }

        [Required(ErrorMessage ="Müşteri Adı boş geçirilemez")]
        [StringLength(50,ErrorMessage ="En fazla 50 karakterlik geçerlidir")]
        public string MUSTERIAD { get; set; }

        [Required(ErrorMessage = "Müşteri Soyadı boş geçirilemez")]
        public string MUSTERISOYAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
